# Generated by Django 4.0.5 on 2022-06-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words_learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['add_date']},
        ),
    ]
