# Generated by Django 4.0.5 on 2022-06-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words_learn', '0002_alter_library_options_alter_word_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translate',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
