# Generated by Django 4.0.5 on 2022-07-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words_learn', '0003_word_translate_alter_library_name_alter_word_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='image',
            field=models.ImageField(default='temp.png', upload_to=''),
            preserve_default=False,
        ),
    ]
